[[redirects]]
  from = "/"
  to = "/home"
  status = 200
[[redirects]]
  from = "/about"
  to = "/about"
  status = 200
[[redirects]]
  from = "/contact"
  to = "/contact"
  status = 200
[[redirects]]
  from = "/portfolio"
  to = "/portfolio"
  status = 200